Repository kaaaaakun/ft_transcendence, pull requests merged in 2024-09, with the labels that each got.

#26 docker composeの更新
  docker-compose.local.yml
  docker-compose.yml
Labels: frontend

#35 Api dockercompose & dockerfile
  .env.sample
  api/Dockerfile
  docker-compose.local.yml
  docker-compose.yml
Labels: backend

#29 add useCallback hook
  static-builder/README.md
  static-builder/docker-compose.yml
  static-builder/src/js/components/InputAlias.js
  static-builder/src/js/components/common/Title.js
  static-builder/src/js/components/ui/button.js
  static-builder/src/js/main.js
  static-builder/src/js/teact.js
  static-builder/src/js/test/svg_test.js
Labels: frontend

#30 Router
  static-builder/README.md
  static-builder/src/js/components/InputAlias.js
  static-builder/src/js/components/common/Header.js
  static-builder/src/js/components/common/Title.js
  static-builder/src/js/components/ui/button.js
  static-builder/src/js/features/tournament/Tournament.js
  static-builder/src/js/layouts/BaseLayout.js
  static-builder/src/js/libs/router.js
  static-builder/src/js/libs/teact.js
  static-builder/src/js/main.js
  static-builder/src/js/pages/Home.js
  static-builder/src/js/test/svg_test.js
  static-builder/src/js/test/tournament.js
Labels: frontend

#43 create pong
  static-builder/index.html
  static-builder/src/js/components/InputAlias.js
  static-builder/src/js/components/ui/button.js
  static-builder/src/js/features/pong/Pong.js
  static-builder/src/js/features/tournament/Tournament.js
  static-builder/src/js/test/pong.js
  static-builder/src/js/test/tournament.js
Labels: frontend

#45 Integration: update makefile
  Makefile
Labels: enhancement

#48 create 4player tournament
  static-builder/src/js/components/ui/button.js
  static-builder/src/js/features/tournament/Tournament.js
  static-builder/src/js/test/tournament.js
Labels: frontend

#51 Api enhancement error handling
  api/conf/app_match/utils.py
  api/conf/app_match/views.py
  api/conf/app_player/utils.py
  api/conf/app_tournament/utils.py
  api/conf/app_tournament/views.py
Labels: enhancement, backend

#50 2player tournament
  static-builder/src/js/features/tournament/Tournament.js
Labels: frontend

#53 Add use location use navigation hooks
  static-builder/src/js/libs/router.js
  static-builder/src/js/libs/teact.js
  static-builder/src/js/main.js
  static-builder/src/js/pages/Home.js
Labels: frontend

#54 Change toppage
  static-builder/src/js/features/tournament/Tournament.js
  static-builder/src/js/main.js
  static-builder/src/js/pages/Home.js
  static-builder/src/js/pages/InputAlias.js
  static-builder/src/js/pages/Pong.js
  static-builder/src/js/pages/Tournament.js
  static-builder/src/js/test/input_alias.js
Labels: frontend

#56 Api utils
  .env.sample
  Makefile
  docker-compose.local.yml
  docker-compose.yml
  reverseproxy/nginx.conf
  reverseproxy/nginx.local.conf
  static-builder/README.md
  static-builder/docker-compose.yml
  static-builder/src/js/infrastructures/api/fetch.js
  static-builder/src/js/infrastructures/api/tournamentApi.js
Labels: frontend

#58 fix setState not working in useEffect
  static-builder/src/js/libs/teact.js
Labels: frontend

#61 unable header link
  static-builder/src/js/components/common/Header.js
  static-builder/src/scss/styles.scss
Labels: frontend

#59 Use django api
  static-builder/src/js/pages/InputAlias.js
  static-builder/src/js/pages/Pong.js
  static-builder/src/js/pages/Tournament.js
Labels: frontend

#62 Return tournament
  static-builder/src/js/infrastructures/api/tournamentApi.js
  static-builder/src/js/infrastructures/cookie/cookie.js
  static-builder/src/js/pages/Home.js
  static-builder/src/js/pages/InputAlias.js
  static-builder/src/js/pages/Pong.js
  static-builder/src/js/pages/Tournament.js
Labels: frontend

#60 fi x create_tournament_dataset create_ponggame_dataset
  api/Dockerfile
  api/README.md
  api/conf/app_match/tests.py
  api/conf/app_match/utils.py
  api/conf/app_match/views.py
  api/conf/app_tournament/utils.py
Labels: backend

#64 fix sorted
  api/conf/app_match/utils.py
Labels: backend

#63 add the button to launch the ball
  static-builder/src/js/pages/Pong.js
Labels: frontend
